name: LeafFragmentos
version: 0.0.1
depend: [MVdWPlaceholderAPI]
main: me.czergames.fragmentos.Main
author: CzerGamesBR_

commands:
  fragmentos:
    aliases: [frags]
    description: Comando para exibir quantidade de fragmentos...